### ISSUE TITLE
ConfigException in rdf_loader.config

### ISSUE THREAD

**Issue by amgadmadkour** [SANSA-Stack/SANSA-Template-Maven-Spark#1]
The following exception is thrown when trying to read an NT file using the following line
```
triplesDF = spark.read.rdf(lang)(input)
```
The exception is as follows:
```
Exception in thread "main" com.typesafe.config.ConfigException$Parse: rdf_loader.conf
```
Workaround was to upgrade SANSA snapshot version to ```0.3.1``` instead of ```0.3.0```. Seems the version just needs to be bumped in the POM to resolve this issue.

**Comment by GezimSejdiu** [comment]
Hi @amgadmadkour ,
once again many thanks for your findings. I just bumped the SANSA version into 0.3.1-SNAPSHOT which resolve this issue.

Best regards, 
Gezim
